before:
  hooks:
    - make ensure
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
archives:
- replacements:
    darwin: macos
    linux: linux
    windows: windows
    386: 32-bit
    amd64: 64-bit
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}-checksums.txt'
snapshot:
  name_template: "{{ .Version }}_{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
